# Temario y referencias {-}

**Todas las notas y material del curso estarán en este** [repositorio](https://github.com/felipegonzalez/aprendizaje-maquina-mcd-2023).

- Introducción al aprendizaje máquina
- Métodos locales y estructurados. Ingeniería de variables de entrada. 
- Principios de Regularización
- Problemas de clasificación, métricas y evaluación
- Métodos de remuestreo y validación cruzada
- Redes neuronales
- Árboles, bosques aleatorios y boosting
- Diagnóstico y mejora en problemas de aprendizaje supervisado
- Reducción de dimensionalidad: Embeddings, descomposición en valores singulares, componentes principales
- Análisis de conglomerados

### Evaluación {-}

- Tareas semanales (20%) para discutir en clase, compartidas en el repositorio y en nuestro espacio de trabajo de Posit Cloud.
- Examen parcial (40% práctico), con una componente oral.
- Un examen final (20% práctico), con una componente oral.

### Material {-}

Cada semestre las notas cambian, en algunas partes considerablemente. Las
de este semestre están en [este repositorio](https://github.com/felipegonzalez/aprendizaje-maquina-mcd-2023),
incluyendo ejemplos, ejercicios y tareas.

### Referencias principales {-}

- [An Introduction to Statistical Learning](https://www.statlearning.com/), @ISL 
- [Deep Learning](https://www.deeplearningbook.org/), @goodfellow2016
- [Tidy Modeling with R](https://www.tmwr.org/), @kuhn2022tidy

### Otras referencias {-}

- [Pattern Recognition and Machine Learning](http://www.springer.com/us/book/9780387310732), @Bishop
- [The Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/), @ESL
- [Predicción conforme](https://people.eecs.berkeley.edu/~angelopoulos/blog/posts/gentle-intro/)

### Software {-}

Para hacer las tareas y exámenes pueden usar cualquier lenguaje o flujo de trabajo
que les convenga (R o Python, por ejemplo) - el único requisito esté basado en código y no
point-and-click. En lo posible utilizamos librerías especializadas
que se pueden utilizar desde varias plataformas (keras, por ejemplo).


